Convert PullRequests to pipeline of jobs
- PRs currently run in separate, stand-alone jobs
  and this is not maintenance friendly.
- There are many benefits to switching to the common
  workflow of "pipeline of jobs" used by all other builds.
- This PR adds support for PR builds to use
  Pipeline-Build-Test-All as a top-level job.
- This also adds support in pipeline-functions to accomodate
  various functionality needed by PRs.
- Update README to reflect changes.
- Auto-Cancel Test jobs when new ones are launched from the same PR

Issue #2728
[skip ci]

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

diff --git a/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All b/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
--- a/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
+++ b/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
@@ -88,6 +88,20 @@ SPECS = ['aix_ppc-64_cmprssptrs'      : CURRENT_RELEASES,
          'osx_x86-64'                 : CURRENT_RELEASES,
          'osx_x86-64_cmprssptrs'      : CURRENT_RELEASES]
 
+// SHORT_NAMES is used for PullRequest triggers
+// TODO Combine SHORT_NAMES and SPECS
+SHORT_NAMES = ['all' : 'all',
+            'aix' : 'aix_ppc-64_cmprssptrs',
+            'zlinux' : 'linux_390-64_cmprssptrs',
+            'plinux' : 'linux_ppc-64_cmprssptrs_le',
+            'xlinuxlargeheap' : 'linux_x86-64',
+            'xlinux' : 'linux_x86-64_cmprssptrs',
+            'xlinuxcmake' : 'linux_x86-64_cmprssptrs_cmake',
+            'win32' : 'win_x86',
+            'win' : 'win_x86-64_cmprssptrs',
+            'osx' : 'osx_x86-64_cmprssptrs',
+            'osxlargeheap' : 'osx_x86-64']
+
 // Initialize all PARAMETERS (params) to Groovy Variables even if they are not passed
 echo "Initialize all PARAMETERS..."
 SETUP_LABEL = (params.SETUP_LABEL) ? params.SETUP_LABEL : "worker"
@@ -111,6 +125,20 @@ echo "BUILD_LIST:'${BUILD_LIST}'"
 BUILD_IDENTIFIER = (params.BUILD_IDENTIFIER) ? params.BUILD_IDENTIFIER : ""
 echo "BUILD_IDENTIFIER:'${BUILD_IDENTIFIER}'"
 
+// Pull Request Builds
+ghprbPullId = (params.ghprbPullId) ? params.ghprbPullId : ""
+echo "ghprbPullId:'${ghprbPullId}'"
+ghprbGhRepository = (params.ghprbGhRepository) ? params.ghprbGhRepository : ""
+echo "ghprbGhRepository:'${ghprbGhRepository}'"
+ghprbCommentBody = (params.ghprbCommentBody) ? params.ghprbCommentBody : ""
+echo "ghprbCommentBody:'${ghprbCommentBody}'"
+ghprbTargetBranch = (params.ghprbTargetBranch) ? params.ghprbTargetBranch : ""
+echo "ghprbTargetBranch:'${ghprbTargetBranch}'"
+ghprbActualCommit = (params.ghprbActualCommit) ? params.ghprbActualCommit : ""
+echo "ghprbActualCommit:'${ghprbActualCommit}'"
+
+VERSION_MAP = initialize_version_map()
+
 OPENJDK_REPO = [:]
 OPENJDK_BRANCH = [:]
 OPENJDK_SHA = [:]
@@ -123,22 +151,115 @@ timeout(time: 12, unit: 'HOURS') {
         node(SETUP_LABEL) {
             try {
                 checkout scm
-                def variableFile = load 'buildenv/jenkins/common/variables-functions'
+                variableFile = load 'buildenv/jenkins/common/variables-functions'
                 buildFile = load 'buildenv/jenkins/common/pipeline-functions'
 
-                BUILD_SPECS.putAll(get_specs(SPECS))
+                // Determine if build is a PullRequest
+                if (ghprbPullId) {
+                    // Parse Github trigger comment
+                    // Jenkins test sanity <platform>*
+                    // Jenkins test extended <platform>*
+                    // Jenkins compile <platform>*
+                    // Jenkins test <comma_separated_test_target> <platform> *
+                    //params.TESTS_TARGETS = params.ghprbCommentBody.substring(?)
+                    /*
+                    * Comment indexes - '+' is an offset of 0/1 if running tests or not
+                    * 0 - Jenkins
+                    * 1 - test / compile
+                    * 1+ - test target
+                    * 2+ - platforms
+                    * 3+ - jdk versions
+                    */
+                    def PARSED_COMMENT = params.ghprbCommentBody.toLowerCase().tokenize(' ')
+                    if (PARSED_COMMENT[0] != 'adam') {
+                        error("Pull Request trigger comment needs to begin with 'Jenkins'")
+                    }
+
+                    // Setup TESTS_TARGETS
+                    switch ("${PARSED_COMMENT[1]}") {
+                        case "compile":
+                            TESTS_TARGETS = 'none'
+                            OFFSET = 0
+                            break
+                        case "test":
+                            TESTS_TARGETS = "${PARSED_COMMENT[2]}"
+                            if ("${TESTS_TARGETS}" == "all") {
+                                error("Test Target 'all' not allowed for Pull Request builds")
+                            }
+                            OFFSET = 1
+                            break
+                        default:
+                            error("Unable to parse trigger comment. Unknown build option:'${PARSED_COMMENT[1]}'")
+                    }
+                    echo "TESTS_TARGETS:'${TESTS_TARGETS}'"
+
+                    // Setup JDK VERSIONS
+                    switch (ghprbGhRepository) {
+                        case   ~/.*openj9-openjdk-jdk.*/:
+                            TMP_VERSION = ghprbGhRepository.substring(ghprbGhRepository.indexOf('-jdk')+4)
+                            if ("${TMP_VERSION}" == "") {
+                                TMP_VERSION = 'next'
+                            }
+                            VERSION_MAP["${TMP_VERSION}"] = true
+                            MIN_COMMENT_SIZE = 3
+                            break
+                        case "eclipse/openj9":
+                            TMP_VERSIONS = PARSED_COMMENT[3+OFFSET].tokenize(',')
+                            TMP_VERSIONS.each { VERSION ->
+                                echo "VERSION:'${VERSION}'"
+                                if ("${VERSION}" == "all") {
+                                    error("JDK version 'all' not allowed for Pull Request builds\nExpected 'jdkX' where X is one of ${RELEASES}")
+                                }
+                                if (!("${VERSION}" ==~ /jdk.*/)) {
+                                    error("Incorrect syntax for requested JDK version:'${VERSION}'\nExpected 'jdkX' where X is one of ${RELEASES}")
+                                }
+                                if (RELEASES.contains(VERSION.substring(3))) {
+                                    VERSION_MAP["${VERSION.substring(3)}"] = true
+                                } else {
+                                    error("Unsupported JDK version or incorrect syntax:'${VERSION}'\nExpected 'jdkX' where X is one of ${RELEASES}")
+                                }
+                            }
+                            MIN_COMMENT_SIZE = 4
+                            break
+                        default:
+                            error("Unknown source repo:'${ghprbGhRepository}'")
+                    }
+
+                    echo "VERSION_MAP:'${VERSION_MAP}'"
+
+                    if (PARSED_COMMENT.size() < MIN_COMMENT_SIZE) { error("Pull Request trigger comment does not contain enough elements.")}
+
+                    // Setup PLATFORMS
+                    TMP_PLATFORMS = []
+                    PARSED_PLATFORMS = PARSED_COMMENT[2+OFFSET].tokenize(',')
+                    PARSED_PLATFORMS.each { SHORT ->
+                        LONG_PLATFORM = SHORT_NAMES["${SHORT}"]
+                        if (LONG_PLATFORM) {
+                            TMP_PLATFORMS.add(LONG_PLATFORM)
+                        } else {
+                            error("Unknown PLATFORM short:'${SHORT}'\nExpected one of:${SHORT_NAMES}")
+                        }
+                    }
+                    PLATFORMS = TMP_PLATFORMS.join(',')
+                    echo "PLATFORMS:'${PLATFORMS}'"
+
+                    PERSONAL_BUILD = 'true'
+                }
+
+                BUILD_SPECS.putAll(get_specs(SPECS, VERSION_MAP))
 
                 // parse variables file and initialize variables
                 variableFile.set_job_variables('wrapper')
+
                 SHAS = buildFile.get_shas(OPENJDK_REPO, OPENJDK_BRANCH, OPENJ9_REPO, OPENJ9_BRANCH, OMR_REPO, OMR_BRANCH)
 
-                if (params.PERSONAL_BUILD) {
+                if (PERSONAL_BUILD) {
                     // update build description
-                    currentBuild.description += "<br/>${params.PLATFORMS}"
+                    currentBuild.description += "<br/>${PLATFORMS}"
                 }
 
-                def BUILD_NODES = get_node_labels(params.BUILD_NODE_LABELS, BUILD_SPECS.keySet())
-                def TEST_NODES = get_node_labels(params.TEST_NODE_LABELS, BUILD_SPECS.keySet())
+                def BUILD_NODES = get_node_labels(BUILD_NODE_LABELS, BUILD_SPECS.keySet())
+                def TEST_NODES = get_node_labels(TEST_NODE_LABELS, BUILD_SPECS.keySet())
 
                 BUILD_SPECS.each { SPEC, SDK_VERSIONS ->
                     SDK_VERSIONS.each { SDK_VERSION ->
@@ -168,7 +289,7 @@ timeout(time: 12, unit: 'HOURS') {
         // launch all pipeline builds
         parallel builds
 
-        if (params.PROMOTE_OMR) {
+        if (PROMOTE_OMR) {
             stage('Promote') {
                 ghprbGhRepository = OPENJ9_REPO.substring(OPENJ9_REPO.indexOf('.com') +5, OPENJ9_REPO.indexOf('.git'))
                 ghprbActualCommit = SHAS['OPENJ9']
@@ -209,38 +330,43 @@ def build(OPENJDK_REPO, OPENJDK_BRANCH, SHAS, OPENJ9_REPO, OPENJ9_BRANCH, OMR_RE
                     string(name: 'RESTART_TIMEOUT_UNITS', value: RESTART_TIMEOUT_UNITS),
                     string(name: 'SETUP_LABEL', value: SETUP_LABEL),
                     string(name: 'BUILD_LIST', value: BUILD_LIST),
-                    string(name: 'BUILD_IDENTIFIER', value: BUILD_IDENTIFIER)]
+                    string(name: 'BUILD_IDENTIFIER', value: BUILD_IDENTIFIER),
+                    string(name: 'ghprbPullId', value: ghprbPullId),
+                    string(name: 'ghprbGhRepository', value: ghprbGhRepository),
+                    string(name: 'ghprbCommentBody', value: ghprbCommentBody),
+                    string(name: 'ghprbTargetBranch', value: ghprbTargetBranch),
+                    string(name: 'ghprbActualCommit', value: ghprbActualCommit)]
         return JOB
     }
 }
 
-/**
- * Parses the build parameters to identify the specs and the releases to build
- * and test. Returns a map of releases by specs.
- */
-def get_specs(SUPPORTED_SPECS) {
+/*
+* Parses the build parameters to identify the specs and the releases to build
+* and test. Returns a map of releases by specs.
+*/
+def get_specs(SUPPORTED_SPECS, VERSION_MAP) {
     def RELEASES = []
-    def PLATFORMS = []
+    def PARSED_PLATFORMS = []
     def SPECS = [:]
 
     // get releases 
-    params.each { key, value  ->
-        if ((key.indexOf('Java') != -1) && (value == true)) {
-            RELEASES.add(key.substring(4))
+    VERSION_MAP.each { key, value  ->
+        if (value) {
+            RELEASES.add(key)
         }
     }
 
     // get specs
-    if (!params.PLATFORMS || (params.PLATFORMS.trim() == 'all')) {
+    if (!PLATFORMS || (PLATFORMS.trim() == 'all')) {
         // build and test all supported specs
-        PLATFORMS.addAll(SUPPORTED_SPECS.keySet())
+        PARSED_PLATFORMS.addAll(SUPPORTED_SPECS.keySet())
     } else {
-        PLATFORMS.addAll(params.PLATFORMS.split(","))
+        PARSED_PLATFORMS.addAll(PLATFORMS.split(","))
     }
 
     def RELEASES_STR = RELEASES.join(',')
 
-    PLATFORMS.each { SPEC ->
+    PARSED_PLATFORMS.each { SPEC ->
         SPEC = SPEC.trim()
         if (!SUPPORTED_SPECS.keySet().contains(SPEC)) {
             echo "Warning: Unknown or unsupported platform: ${SPEC}"
@@ -263,7 +389,7 @@ def get_specs(SUPPORTED_SPECS) {
     }
 
     if (!SPECS) {
-        error("Invalid PLATFORMS (${params.PLATFORMS}) and/or Java versions selections(${RELEASES_STR})!")
+        error("Invalid PLATFORMS (${PLATFORMS}) and/or Java versions selections(${RELEASES_STR})!")
     }
 
     return SPECS
@@ -300,7 +426,7 @@ def get_node_labels(NODE_LABELS, SPECS) {
             }
 
             if (!SPECS.contains(ENTRY[0].trim())) {
-                error("Wrong node labels platform: ${ENTRY[0]} in ${ITEM}! It does not match any of your selected platforms: ${params.PLATFORMS}")
+                error("Wrong node labels platform: ${ENTRY[0]} in ${ITEM}! It does not match any of your selected platforms: ${PLATFORMS}")
             }
 
             LABELS.put(ENTRY[0].trim(), ENTRY[1].trim())
@@ -308,4 +434,19 @@ def get_node_labels(NODE_LABELS, SPECS) {
     }
 
     return LABELS
+}
+
+/*
+* Returns a map of the Java Version bools.
+* Ie. MAP = [8:true, 9:false, 10:true] etc
+*/
+def initialize_version_map() {
+    def VERSION_MAP = [:]
+    params.each { key, value  ->
+        if ((key.indexOf('Java') != -1) && (value == true)) {
+            VERSION_MAP["${key.substring(4)}"] = value
+        }
+    }
+    echo "Initial VERSION_MAP:'${VERSION_MAP}'"
+    return VERSION_MAP
 }
